version: '2'

services:
  graphite:
    build: ./graphite
    image: graphite:1.0.0
    ports:
      - 2003:2003
    volumes:
      - whisper:/opt/graphite/storage/whisper
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    restart: always
    links:
      - graphite

volumes:
  whisper:
  grafana:
