FROM sitespeedio/graphite

ADD config/storage-schemas.conf /opt/graphite/conf/storage-schemas.conf
ADD config/local_settings.py /opt/graphite/webapp/graphite/local_settings.py
ADD config/carbon.conf /opt/graphite/conf/carbon.conf

EXPOSE 80 2003 2004
